services:
  - type: web
    name: ai-analyst-backend
    runtime: docker
    repo: https://github.com/Sahilnegi4444/Ai-Analyst-Agent
    branch: main
    region: oregon
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ENABLE_RERANKER
        value: "false"
      - key: EMBEDDING_MODEL_NAME
        value: all-MiniLM-L6-v2
      - key: RERANK_MODEL_NAME
        value: cross-encoder/ettin-reranker-17m-v1
      - key: GROQ_ROUTER_MODEL
        value: llama-3.1-8b-instant
      - key: GROQ_SQL_MODEL
        value: llama-3.1-8b-instant
      - key: GROQ_GENERATOR_MODEL
        value: llama-3.3-70b-versatile
      - key: REDIS_CACHE_TTL
        value: "3600"
