from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class ChatRequest(BaseModel):
    """
    Pydantic model representing a chat request from a user.
    """
    query: str = Field(..., description="The natural language question from the user.")

class SourceAttribution(BaseModel):
    """
    Pydantic model representing a document source match.
    """
    filename: str = Field(..., description="Name of the PDF file.")
    title: str = Field(..., description="Document title.")
    content_snippet: str = Field(..., description="Snippet of matching text.")
    confidence: float = Field(..., description="Similarity confidence score.")

class ChatResponse(BaseModel):
    """
    Pydantic model representing the agent's full processed response.
    """
    query: str = Field(..., description="The original user question.")
    intent: str = Field(..., description="The detected routing intent.")
    final_response: str = Field(..., description="The generated natural language answer.")
    status: str = Field("success", description="Response status (e.g. success, insufficient_data).")
    sql_generated: Optional[str] = Field(None, description="The SQL query generated by the agent (if applicable).")
    sql_results: Optional[List[Dict[str, Any]]] = Field(None, description="Raw rows returned by the SQL engine.")
    sources: Optional[List[SourceAttribution]] = Field(None, description="Document chunks matched via RAG vector search.")
    latency_seconds: float = Field(..., description="Overall latency for the agent invocation in seconds.")
    cached: bool = Field(False, description="Whether the response was served from cache.")
