from typing import Any

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """
    Pydantic model representing a chat request from a user.
    """
    query: str = Field(..., description="The natural language question from the user.")
    session_id: str | None = Field(None, description="The session or conversation identifier.")

class SourceAttribution(BaseModel):
    """
    Pydantic model representing a document source match.
    """
    filename: str = Field(..., description="Name of the PDF file.")
    title: str = Field(..., description="Document title.")
    content_snippet: str = Field(..., description="Snippet of matching text.")
    confidence: float = Field(..., description="Similarity confidence score.")

class ChatResponse(BaseModel):
    """
    Pydantic model representing the agent's full processed response.
    """
    query: str = Field(..., description="The original user question.")
    intent: str = Field(..., description="The detected routing intent.")
    final_response: str = Field(..., description="The generated natural language answer.")
    status: str = Field("success", description="Response status (e.g. success, insufficient_data).")
    sql_generated: str | None = Field(None, description="The SQL query generated by the agent (if applicable).")
    sql_results: list[dict[str, Any]] | None = Field(None, description="Raw rows returned by the SQL engine.")
    sources: list[SourceAttribution] | None = Field(None, description="Document chunks matched via RAG vector search.")
    latency_seconds: float = Field(..., description="Overall latency for the agent invocation in seconds.")
    cached: bool = Field(False, description="Whether the response was served from cache.")

class MessageHistoryItem(BaseModel):
    """
    Pydantic model representing a past message in a session.
    """
    id: int
    session_id: str
    sender: str
    text: str
    intent: str | None = None
    sql_generated: str | None = None
    sql_results: list[dict[str, Any]] | None = None
    sources: list[SourceAttribution] | None = None
    latency_seconds: float | None = None
    cached: bool | None = None
    status: str | None = None
    timestamp: Any

class MessageHistoryResponse(BaseModel):
    """
    Pydantic model representing list of messages in history.
    """
    messages: list[MessageHistoryItem]

class SessionListResponse(BaseModel):
    """
    Pydantic model representing the list of active sessions.
    """
    sessions: list[str]
