"""create_chat_messages_table

Revision ID: 786a19874714
Revises: 66fe5fdddba2
Create Date: 2026-07-14 12:24:23.143617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786a19874714'
down_revision: Union[str, Sequence[str], None] = '66fe5fdddba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('sender', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('sql_generated', sa.Text(), nullable=True),
    sa.Column('sql_results', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('latency_seconds', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
